Completed prep-html-skeleton exercise :D - Andrew Almeida
A-MAlmeida/prep-0721-code-solutions pull request #2
Opened 2021-07-31 20:40 UTC by A-MAlmeida

![5B5F87EC-0372-467B-A4E9-4A9C2EE9D827](https://user-images.githubusercontent.com/88172707/127751949-5f711351-36e1-45f8-b177-92f76af1154c.jpeg)

2021-08-01 16:53 UTC, thebearingedge requested changes

2021-08-01 16:53 UTC, thebearingedge commented on prep-html-skeleton/index.html
> +  </head>
Hi Andrew, be sure to divide your page into two specific sections. The `<head>` should open and close be fore the `<body>` opens and closes. The visible content of the page should go in the `<body>`.

```html
<!DOCTYPE html>
<html>
  <head>
    <!-- meta info like <title></title> goes in here -->
  </head>
  <body>
    <!-- visible content like <h1></h1> and <p></p> goes in here -->
  </body>
</html>
```

2021-08-02 21:23 UTC, A-MAlmeida commented
![C40F156F-297F-4925-BB88-F3B20EDEE3C6](https://user-images.githubusercontent.com/88172707/127925537-07e34caf-a63f-45c4-8ca1-7603b15cd390.jpeg)

2021-08-02 21:25 UTC, A-MAlmeida commented
Do I have to create a new pull request?
I've already pushed the updated assignment through.

thanks for your help!

2021-08-02 21:28 UTC, thebearingedge approved these changes

2021-08-02 21:28 UTC, thebearingedge commented
All good!

2021-08-02 21:29 UTC, A-MAlmeida commented
YEAHHHHHHH
thank ya

2021-08-02 21:29 UTC, merged