Completed prep-css-flexbox exercise - Andrew Almeida
A-MAlmeida/prep-0721-code-solutions pull request #8
Opened 2021-08-07 04:07 UTC by A-MAlmeida

![030021A5-8880-4096-AE18-F4C930D64DAF_1_105_c](https://user-images.githubusercontent.com/88172707/128587348-59f3b865-722b-45d0-86dc-edc6fafabeaa.jpeg)
<img width="1331" alt="Screen Shot 2021-08-06 at 9 02 06 PM" src="https://user-images.githubusercontent.com/88172707/128587354-4c37e865-c641-460b-899d-15f635546303.png">
<img width="1331" alt="Screen Shot 2021-08-06 at 9 02 21 PM" src="https://user-images.githubusercontent.com/88172707/128587355-788ff5e0-533b-4eaf-af87-e81879fd00f4.png">
<img width="1331" alt="Screen Shot 2021-08-06 at 9 02 30 PM" src="https://user-images.githubusercontent.com/88172707/128587360-1b353490-7f71-435d-8a68-5b4ef161606d.png">

2021-08-07 15:19 UTC, thebearingedge requested changes

2021-08-07 15:19 UTC, thebearingedge commented on prep-css-flexbox/display-flex.html
> +    /* your styles here 👇 */
Hi Andrew, looks like your HTML files didn't get save/added in the right order. Be sure to save them in VS Code before doing the `git add` step.

https://github.com/A-MAlmeida/prep-0721-code-solutions/pull/8/files

2021-08-09 00:54 UTC, A-MAlmeida commented
![B00A9E11-CF2C-4447-A06C-1F7B5FCB4281_1_105_c](https://user-images.githubusercontent.com/88172707/128651190-d09f97b3-70ab-4b77-95d2-a4d359b34750.jpeg)

2021-08-10 02:19 UTC, thebearingedge requested changes
Hi Andrew, somethings up. For some reason your HTML files are missing most of their CSS

https://github.com/A-MAlmeida/prep-0721-code-solutions/pull/8/files

2021-08-10 07:23 UTC, A-MAlmeida commented
![D34C9A58-79B2-465B-A7EA-B02033D319C2_1_105_c](https://user-images.githubusercontent.com/88172707/128825316-2358b23c-502d-46de-84fe-90f2194949f5.jpeg)
![BB219564-D0A6-40B2-AFE2-B496CBDBD40B_1_105_c](https://user-images.githubusercontent.com/88172707/128825324-86f2ee88-f429-4497-ad43-c17051875c7f.jpeg)
![9BE87761-BA30-4261-A5B8-81058BA998F7_1_105_c](https://user-images.githubusercontent.com/88172707/128825333-2cd1e0be-4c2a-40b2-929e-60387875d1f3.jpeg)
![9C529BDF-6055-430B-A9E4-98FD63F1B183](https://user-images.githubusercontent.com/88172707/128825336-309ecbbf-6502-4e36-98b0-f110cc3bf82e.jpeg)

2021-08-10 22:31 UTC, thebearingedge approved these changes
Got it!

2021-08-11 01:55 UTC, merged